version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: gms/circleci_node_gms:latest
        auth:
          username: gms46
          #password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          password: fd0277d6-3859-44ce-8ac1-d37606afd061
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: gms/circleci_node_gms:latest
        auth:
          username: gms46
          password: fd0277d6-3859-44ce-8ac1-d37606afd061 # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test