jobs:
  build:
    docker:
      # Primary Executor
      - image: circleci/openjdk:11.0-jdk
        auth:
          username: GMS46
          password: beer$larval=money  # context / project UI env-var reference

      # Dependency Service(s)
      - image: postgres:10.8
        auth:
          username: GMS46
          password: beer$larval=money  # context / project UI env-var reference
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres